# Generated by Django 5.2 on 2026-02-07 21:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_parcelle_delete_parcelles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
